// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXT-E0WUSGgU2y9VTctD7SaVGcGJGM6Yk',
    appId: '1:339968263889:web:8140c29474b00de44267f0',
    messagingSenderId: '339968263889',
    projectId: 'instagramclone-4b53a',
    authDomain: 'instagramclone-4b53a.firebaseapp.com',
    storageBucket: 'instagramclone-4b53a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABewhtlZ7ff5f6e5A5w4UFtg_0T1ESd-c',
    appId: '1:339968263889:android:6690503ab442837d4267f0',
    messagingSenderId: '339968263889',
    projectId: 'instagramclone-4b53a',
    storageBucket: 'instagramclone-4b53a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzceCGKIByMrS35hTYfzKX2Csq-9ls2uA',
    appId: '1:339968263889:ios:dbb8ead1625909cd4267f0',
    messagingSenderId: '339968263889',
    projectId: 'instagramclone-4b53a',
    storageBucket: 'instagramclone-4b53a.appspot.com',
    iosClientId: '339968263889-899kfqsulb0elga3dl6458dg15as7ctc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzceCGKIByMrS35hTYfzKX2Csq-9ls2uA',
    appId: '1:339968263889:ios:dbb8ead1625909cd4267f0',
    messagingSenderId: '339968263889',
    projectId: 'instagramclone-4b53a',
    storageBucket: 'instagramclone-4b53a.appspot.com',
    iosClientId: '339968263889-899kfqsulb0elga3dl6458dg15as7ctc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
